### ISSUE TITLE
twitter.error.TwitterError: Text must be less than or equal to CHARACTER_LIMIT characters.

### ISSUE THREAD

**Issue by kmyk** [kotatsugame/atgolfer#14]
``` python
Traceback (most recent call last):
  File "/home/ubuntu/atgolfer/main.py", line 290, in <module>
    main()
  File "/home/ubuntu/atgolfer/main.py", line 271, in main
    raise e
  File "/home/ubuntu/atgolfer/main.py", line 266, in main
    post_text(data['text'], in_reply_to_status_id=last_status_id.get(data['problem_id']))
  File "/home/ubuntu/atgolfer/main.py", line 253, in post_text
    status = api.PostUpdate(text, in_reply_to_status_id=in_reply_to_status_id)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/twitter/api.py", line 1113, in PostUpdate
    raise TwitterError("Text must be less than or equal to CHARACTER_LIMIT characters.")
twitter.error.TwitterError: Text must be less than or equal to CHARACTER_LIMIT characters.
```

**Comment by kmyk** [comment]
問題名が長いのやめろ :anger:

```
お誕生日コンテスト: X - この問題はほんとうにひどい問題であるため，できれば先に他の問題のほうをお楽しみいただければと思っておりまして，ですので他の問題を通し終えて暇になり，かつその暇を
luogu_bot5 さんが paulzrm さんからショートコードを奪取しました！ (55570 Byte → 37498 Byte)
https://atcoder.jp/contests/birthday0410/submissions/7327135
```

**Comment by kmyk** [comment]
:ok_hand: https://twitter.com/atgolfer1/status/1169225196164677633
