### ISSUE TITLE
AtGolferが動いていないように見えます 2020/03/08

### ISSUE THREAD

**Issue by kmyk** [kotatsugame/atgolfer#16]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr"><a href="https://twitter.com/kimiyuki_u?ref_src=twsrc%5Etfw">@kimiyuki_u</a> AtGolferが動いていないように見えます</p>&mdash; こたつがめ (@kotatsugame_t) <a href="https://twitter.com/kotatsugame_t/status/1236576980444655616?ref_src=twsrc%5Etfw">March 8, 2020</a></blockquote>

cc @kotatsugame

**Comment by kmyk** [comment]
Twitter 側の一時的な不調の影響かな？

``` python
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/twitter/api.py", line 4897, in _ParseAndCheckTwitter
    data = json.loads(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/atgolfer/main.py", line 298, in <module>
    main()
  File "/home/ubuntu/atgolfer/main.py", line 279, in main
    raise e
  File "/home/ubuntu/atgolfer/main.py", line 274, in main
    post_text(data['text'], in_reply_to_status_id=last_status_id.get(data['problem_id']))
  File "/home/ubuntu/atgolfer/main.py", line 261, in post_text
    status = api.PostUpdate(text, in_reply_to_status_id=in_reply_to_status_id)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/twitter/api.py", line 1176, in PostUpdate
    resp = self._RequestUrl(url, 'POST', data=parameters)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/twitter/api.py", line 4962, in _RequestUrl
    limit = self.CheckRateLimit(url)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/twitter/api.py", line 4809, in CheckRateLimit
    self.InitializeRateLimit()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/twitter/api.py", line 4792, in InitializeRateLimit
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/twitter/api.py", line 4907, in _ParseAndCheckTwitter
    raise TwitterError({'Unknown error': '{0}'.format(json_data)})
twitter.error.TwitterError: {'Unknown error': ''}
```

**Comment by kmyk** [comment]
再実行をかけたら問題なく動いた

**Comment by kmyk** [comment]
原因不明ですが、close……
