### ISSUE TITLE
管理者権限を持っているコンテストをうまくクロールできない

### ISSUE THREAD

**Issue by kotatsugame** [kotatsugame/atgolfer#26]
```
[*] GET https://atcoder.jp/contests/tupc2022/submissions
Traceback (most recent call last):
  File "main.py", line 362, in <module>
    main()
  File "main.py", line 343, in main
    raise e
  File "main.py", line 337, in main
    for data in gen:
  File "main.py", line 301, in read_atcoder_problems
    for data in crawl_contest(contest, shortest_codes=shortest_codes, latest_submission_ids=latest_submission_ids):
  File "main.py", line 129, in crawl_contest
    latest_submission_id = int(submission_trs[0].find_all('td')[4]['data-id'])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
KeyError: 'data-id'
```

**Comment by kotatsugame** [comment]
```
<tr>
	<td><input type="checkbox" form="rejudge-form" name="submission_ids[]" value="42966617"></td>
	<td class="no-break"><time class='fixtime fixtime-second'>2023-06-26 01:27:54+0900</time></td>
	<td><a href="/contests/tupc2022/tasks/tupc2022_l">L - Inversion High and Low</a></td>
	<td><a href="/users/Rubikun">Rubikun</a> <a href='/contests/tupc2022/submissions?f.User=Rubikun'><span class='glyphicon glyphicon-search black' aria-hidden='true' data-toggle='tooltip' title='Rubikunさんの提出を見る'></span></a></td>
	<td><a href="/contests/tupc2022/submissions?f.Language=4003">C&#43;&#43; (GCC 9.2.1)</a></td>
	<td class="text-right submission-score" data-id="42966617">400</td>
	<td class="text-right">2583 Byte</td>
	<td class='text-center'><span class='label label-success' data-toggle='tooltip' data-placement='top' title="正解">AC</span></td><td class='text-right'>29 ms</td><td class='text-right'>3848 KB</td>
	<td class="text-center">
		<a href="/contests/tupc2022/submissions/42966617">詳細</a>
	</td>
</tr>
```

0番目に提出のリジャッジを行うためのチェックボックスが入ってずれている。key-errorをキャッチして5番を読み直せばよさそう
